// Generated by CoffeeScript 1.7.1
(function() {
  var crypto, sheesh;

  crypto = require('crypto');

  sheesh = function(input) {
    var shasum;
    shasum = crypto.createHash('sha1');
    shasum.update(input, 'utf8');
    return shasum.digest('hex');
  };

  module.exports = sheesh;

}).call(this);
